package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/saker-ai/ctxhub/internal/domain"
	"golang.org/x/crypto/argon2"
)

// fixedAppSalt is the fallback salt for argon2id when LocalConfig.Salt is
// empty. It is deterministic so that the same passphrase produces the same
// master key across processes — critical for decryption. The salt is
// scoped to OpenViking envelope encryption.
var fixedAppSalt = []byte("openviking-local-kek-salt-v1")

// argon2id parameters used by the local provider when deriving the master
// key from a passphrase. Per the P1 spec: time=3, memory=64MiB, threads=2,
// keyLen=32. They intentionally differ from middleware/auth.go's API-key
// hashing params (time=1, threads=1) because envelope encryption benefits
// from slightly stronger derivation. Reuse is not direct because the auth
// middleware's params are unexported.
const (
	argon2Time    uint32 = 3
	argon2Memory  uint32 = 64 * 1024
	argon2Threads uint8  = 2
	argon2KeyLen  uint32 = 32
)

// LocalProvider wraps DEKs with a 32-byte master key using AES-256-GCM.
// The wrapped form is nonce || ciphertext, so Wrap/Unwrap are self-
// contained (no separate nonce channel).
type LocalProvider struct {
	masterKey []byte
	kdf       string
}

// NewLocal builds a LocalProvider from cfg. When MasterKeyPath is set the
// key is loaded from the file (raw 32 bytes, or a 64-char hex string).
// Otherwise the key is derived from Passphrase via argon2id with the
// configured (or fixed app) salt.
func NewLocal(cfg LocalConfig) (*LocalProvider, error) {
	if cfg.MasterKeyPath != "" {
		mk, err := loadMasterKey(cfg.MasterKeyPath)
		if err != nil {
			return nil, domain.Wrap(domain.CodeInternalError, 500, err)
		}
		return &LocalProvider{masterKey: mk, kdf: KDFFile}, nil
	}
	if cfg.Passphrase == "" {
		return nil, domain.Wrap(domain.CodeValidationFailed, 422,
			errors.New("local crypto: MasterKeyPath or Passphrase is required"))
	}
	salt := cfg.Salt
	if len(salt) == 0 {
		salt = fixedAppSalt
	}
	mk := argon2.IDKey([]byte(cfg.Passphrase), salt,
		argon2Time, argon2Memory, argon2Threads, argon2KeyLen)
	return &LocalProvider{masterKey: mk, kdf: KDFArgon2id}, nil
}

// KDF returns the master-key derivation name ("file" or "argon2id"). The
// Encryptor propagates this into Ciphertext.KDF so consumers can tell how
// the master key was derived.
func (p *LocalProvider) KDF() string { return p.kdf }

// Wrap AES-256-GCM encrypts dek under the master key. The returned blob
// is nonce || ciphertext.
func (p *LocalProvider) Wrap(dek []byte) ([]byte, error) {
	block, err := aes.NewCipher(p.masterKey)
	if err != nil {
		return nil, domain.Wrap(domain.CodeInternalError, 500, err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, domain.Wrap(domain.CodeInternalError, 500, err)
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, domain.Wrap(domain.CodeInternalError, 500, err)
	}
	ct := gcm.Seal(nil, nonce, dek, nil)
	return append(nonce, ct...), nil
}

// Unwrap AES-256-GCM decrypts a nonce||ciphertext blob produced by Wrap.
// A wrong master key or corrupted blob returns an ErrInternal-wrapped
// error so callers can use errors.Is(err, domain.ErrInternal).
func (p *LocalProvider) Unwrap(wrapped []byte) ([]byte, error) {
	block, err := aes.NewCipher(p.masterKey)
	if err != nil {
		return nil, domain.Wrap(domain.CodeInternalError, 500, err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, domain.Wrap(domain.CodeInternalError, 500, err)
	}
	if len(wrapped) < gcm.NonceSize() {
		return nil, domain.Wrap(domain.CodeInternalError, 500,
			errors.New("local crypto: wrapped DEK too short"))
	}
	nonce, ct := wrapped[:gcm.NonceSize()], wrapped[gcm.NonceSize():]
	dek, err := gcm.Open(nil, nonce, ct, nil)
	if err != nil {
		return nil, domain.Wrap(domain.CodeInternalError, 500,
			fmt.Errorf("local crypto: unwrap failed: %w", err))
	}
	return dek, nil
}

// loadMasterKey reads 32 raw bytes or a 64-char hex string from path. The
// hex form mirrors the Python LocalFileProvider which writes the key as
// hex text; the raw-bytes form supports binary key files generated by
// `openssl rand -out key.bin 32` or similar.
func loadMasterKey(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	// Hex form: 64 chars -> 32 bytes.
	if cleaned := strings.TrimSpace(string(data)); len(cleaned) == 64 {
		if b, err := hex.DecodeString(cleaned); err == nil && len(b) == 32 {
			return b, nil
		}
	}
	if len(data) == 32 {
		return data, nil
	}
	return nil, fmt.Errorf("local crypto: master key file %s must contain 32 bytes or 64 hex chars (got %d bytes)", path, len(data))
}
