package migrate

import (
	"archive/zip"
	"bytes"
	"errors"
	"io"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/saker-ai/ctxhub/pkg/ovpack"
)

// writeCorruptablePack writes a deterministic pack into buf so the CLI
// tests can mutate bytes before unpacking.
func writeCorruptablePack(t *testing.T, buf *bytes.Buffer) {
	t.Helper()
	w := ovpack.NewWriter(buf)
	w.SetSource("acct_001", "viking://agent/")
	require.NoError(t, w.WriteResource("viking://agent/resources/docs/readme.md", []byte("hello readme")))
	require.NoError(t, w.WriteSession("01HXYZ", []byte("{\"id\":\"01HXYZ\"}")))
	require.NoError(t, w.Close())
}

func TestCLIRoundTrip(t *testing.T) {
	tmp := t.TempDir()
	src := filepath.Join(tmp, "src")
	dst := filepath.Join(tmp, "dst")
	packPath := filepath.Join(tmp, "snapshot.ovpack")
	require.NoError(t, os.MkdirAll(filepath.Join(src, "resources/docs"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(src, "sessions"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(src, "resources/docs/readme.md"), []byte("hi"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(src, "sessions/01HXYZ.json"), []byte("{}"), 0o644))

	require.NoError(t, packDir(src, packPath, "acct_001", "viking://agent/"))
	require.NoError(t, unpackDir(packPath, dst, false))

	// Files round-trip.
	got, err := os.ReadFile(filepath.Join(dst, "resources/docs/readme.md"))
	require.NoError(t, err)
	assert.Equal(t, "hi", string(got))
	got, err = os.ReadFile(filepath.Join(dst, "sessions/01HXYZ.json"))
	require.NoError(t, err)
	assert.Equal(t, "{}", string(got))

	// Manifest was regenerated by pack and is extracted by unpack.
	manifestPath := filepath.Join(dst, "manifest.json")
	_, err = os.Stat(manifestPath)
	require.NoError(t, err)

	// Re-pack the unpacked dir; should verify cleanly (idempotent).
	repack := filepath.Join(tmp, "snapshot2.ovpack")
	require.NoError(t, packDir(dst, repack, "", ""))
	f, err := os.Open(repack)
	require.NoError(t, err)
	defer f.Close()
	stat, err := f.Stat()
	require.NoError(t, err)
	r, err := ovpack.Open(f, stat.Size())
	require.NoError(t, err)
	require.NoError(t, r.Verify())
}

func TestUnpackDetectsCorruption(t *testing.T) {
	var buf bytes.Buffer
	writeCorruptablePack(t, &buf)

	// Rebuild the zip with one member's content changed. The archive
	// hash recomputed by Verify will not match the manifest's stored
	// archive hash.
	zr, err := zip.NewReader(bytes.NewReader(buf.Bytes()), int64(buf.Len()))
	require.NoError(t, err)
	var corrupted bytes.Buffer
	zw := zip.NewWriter(&corrupted)
	for _, f := range zr.File {
		rc, err := f.Open()
		require.NoError(t, err)
		data, err := io.ReadAll(rc)
		rc.Close()
		require.NoError(t, err)
		if f.Name == "resources/docs/readme.md" {
			data = []byte("JELLO readme")
		}
		w, err := zw.Create(f.Name)
		require.NoError(t, err)
		_, err = w.Write(data)
		require.NoError(t, err)
	}
	require.NoError(t, zw.Close())

	tmp := t.TempDir()
	packPath := filepath.Join(tmp, "bad.ovpack")
	require.NoError(t, os.WriteFile(packPath, corrupted.Bytes(), 0o644))
	dst := filepath.Join(tmp, "dst")

	err = unpackDir(packPath, dst, false)
	require.Error(t, err)
	assert.True(t, errors.Is(err, ovpack.ErrChecksumMismatch), "want ErrChecksumMismatch, got %v", err)

	// skip-verify lets the unpack proceed despite corruption.
	require.NoError(t, unpackDir(packPath, dst, true))
}

func TestPackDirMissingDir(t *testing.T) {
	tmp := t.TempDir()
	missing := filepath.Join(tmp, "does-not-exist")
	out := filepath.Join(tmp, "x.ovpack")
	err := packDir(missing, out, "", "")
	require.Error(t, err)
	_, statErr := os.Stat(out)
	assert.True(t, os.IsNotExist(statErr), "expected no output file on error, got %v", statErr)
}

func TestRootHasOvpackSubcommands(t *testing.T) {
	root := NewRoot()
	cmds := root.Commands()
	names := make([]string, 0, len(cmds))
	for _, c := range cmds {
		names = append(names, c.Name())
	}
	assert.Contains(t, names, "ovpack")
	assert.Contains(t, names, "version")

	ovpackCmd, _, err := root.Find([]string{"ovpack"})
	require.NoError(t, err)
	sub := ovpackCmd.Commands()
	subNames := make([]string, 0, len(sub))
	for _, c := range sub {
		subNames = append(subNames, c.Name())
	}
	assert.Contains(t, subNames, "pack")
	assert.Contains(t, subNames, "unpack")
}

func TestVersionSubcommandStillWorks(t *testing.T) {
	root := NewRoot()
	root.SetArgs([]string{"version"})
	require.NoError(t, root.Execute())
}
