// Package ragfs provides the filesystem-paradigm storage abstraction used
// throughout OpenViking.
//
// ragfs presents resources addressed by viking:// URIs as if they were files
// in a POSIX-like tree. Backends (localfs, memfs, s3fs, ...) implement the
// FileSystem interface; MountableFS routes by URI prefix; MultiWriteFS
// replicates writes across primary + backup backends with sync or async
// fanout. Hidden sidecar files (`.abstract`, `.overview`, `.chunks/`)
// carry L0/L1/L2 layer metadata generated by the ingest pipeline.
//
// The Go implementation mirrors the Rust ragfs crate (crates/ragfs) per the
// design doc section 7.2. It stays an in-process library: no FUSE mount is
// exposed. Sub-packages:
//
//   - internal/ragfs/cache      — metadata cache backends (memory + redis)
//   - internal/ragfs/plugins    — backend implementations (localfs/memfs/s3fs)
//
// The package is intentionally free of network dependencies in its core; only
// the plugin and cache sub-packages pull in aws-sdk / go-redis.
package ragfs
